package com.cloudlbs.core.utils.system;

/**
 * @author Dan Mascenik
 * 
 * @deprecated
 */
public interface SystemPropertyKeys {

	/**
	 * The publicly visible base URL of the system
	 */
	public static final String SYSTEM_PUBLIC_BASE_URL = "system.base.url";

	/**
	 * What to append to the {@link #SYSTEM_PUBLIC_BASE_URL} to get the URL of
	 * the account confirmation servlet
	 */
	public static final String REGISTER_CONFIRM_URLSTUB = "register.confirm.urlstub";

	/**
	 * The "from" email to use when the system sends email to users
	 */
	public static final String MAIL_NOREPLY_ADDRESS = "mail.noreply.address";

	/**
	 * The "from" name to use when the system sends email to users
	 */
	public static final String MAIL_FROM_PRETTYNAME = "mail.from.prettyName";

	/**
	 * The SMTP host to use for sending email
	 */
	public static final String MAIL_HOST = "mail.host";

	/**
	 * The XMPP host to use for chat communications
	 */
	public static final String XMPP_HOST = "xmpp.host";

	/**
	 * The XMPP host to use for chat communications
	 */
	public static final String XMPP_USERNAME_SUFFIX = "xmpp.username.suffix";

	/**
	 * The XMPP hostname as seen outside the firewall
	 */
	public static final String XMPP_EXTERNAL_HOST = "xmpp.external.host";

	/**
	 * The XMPP port as seen outside the firewall
	 */
	public static final String XMPP_EXTERNAL_PORT = "xmpp.external.port";

	/**
	 * The XMPP admin user to connect as
	 */
	public static final String XMPP_ADMIN_USERNAME = "xmpp.admin.username";

	/**
	 * The XMPP admin password
	 */
	public static final String XMPP_ADMIN_PASSWORD = "xmpp.admin.password";

	/**
	 * The max number of processor instances to support
	 */
	public static final String XMPP_MAX_PROCESSORS = "xmpp.max.processors";

	/**
	 * The base-64 encoded private key to use for signature-authenticated calls
	 * as the system's admin user
	 */
	public static final String ADMIN_PRIVATE_KEY = "security.admin.privatekey";

	/**
	 * The base URL of the locations service
	 */
	public static final String SERVICE_LOCATIONS_URL = "services.locations.url";

	/**
	 * The base URL of the accounts service
	 */
	public static final String SERVICE_ACCOUNTS_URL = "services.accounts.url";

	/**
	 * The URL stub for the scope resource on the locations service
	 */
	public static final String RESOURCE_SCOPE_STUB = "resource.scope.urlstub";

	/**
	 * The URL stub for the app resource on the accounts service
	 */
	public static final String RESOURCE_APP_STUB = "resource.app.urlstub";

	/**
	 * The URL stub for the device resource on the accounts service
	 */
	public static final String RESOURCE_DEVICE_STUB = "resource.device.urlstub";

	/**
	 * The URL stub for the session authentication resource on the accounts
	 * service
	 */
	public static final String RESOURCE_SESSION_AUTH_STUB = "resource.sessionAuth.urlstub";

	/**
	 * The URL stub for the signature authentication resource on the accounts
	 * service
	 */
	public static final String RESOURCE_SIGNATURE_AUTH_STUB = "resource.signatureAuth.urlstub";

	/**
	 * The URL stub for the signature authentication resource on the accounts
	 * service
	 */
	public static final String RESOURCE_USER_INTERNAL_STUB = "resource.userInternal.urlstub";

	/**
	 * The URL stub for the processor connection resources on the accounts
	 * service
	 */
	public static final String RESOURCE_PROCESSOR_CONNECTION_STUB = "resource.processorConn.urlstub";

	/**
	 * @deprecated
	 * @author Dan Mascenik
	 *
	 */
	public interface Categories {

		/**
		 * The root "system" namespace
		 */
		public static final String SYSTEM = "system";

		/**
		 * Things related to the user-facing webapp
		 */
		public static final String SYSTEM_WEBAPP = "system.webapp";

		/**
		 * Things related to email generated by the system
		 */
		public static final String SYSTEM_MAIL = "system.mail";

		/**
		 * Things related to authentication and authorization
		 */
		public static final String SYSTEM_SECURITY = "system.security";

		/**
		 * Things related to XMPP services
		 */
		public static final String SYSTEM_XMPP = "system.xmpp";

		/**
		 * Things related to backend services
		 */
		public static final String SYSTEM_SERVICES = "system.services";

	}

}
