// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.cloudlbs.platform.protocol;

public final class AccountProto {
  private AccountProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage.items);
  }
  public interface ServiceAccountMessageOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<ServiceAccountMessage> {
    
    // optional string guid = 1;
    boolean hasGuid();
    String getGuid();
    
    // optional int64 createDate = 2;
    boolean hasCreateDate();
    long getCreateDate();
    
    // optional int64 version = 3;
    boolean hasVersion();
    long getVersion();
    
    // optional string name = 4;
    boolean hasName();
    String getName();
    
    // optional string description = 5;
    boolean hasDescription();
    String getDescription();
    
    // optional string status = 6;
    boolean hasStatus();
    String getStatus();
    
    // optional string scopeGuid = 7;
    boolean hasScopeGuid();
    String getScopeGuid();
    
    // optional string publicKey = 8;
    boolean hasPublicKey();
    String getPublicKey();
    
    // optional string privateKey = 9;
    boolean hasPrivateKey();
    String getPrivateKey();
    
    // repeated string grantedAuthority = 13;
    java.util.List<String> getGrantedAuthorityList();
    int getGrantedAuthorityCount();
    String getGrantedAuthority(int index);
  }
  public static final class ServiceAccountMessage extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        ServiceAccountMessage> implements ServiceAccountMessageOrBuilder {
    // Use ServiceAccountMessage.newBuilder() to construct.
    private ServiceAccountMessage(Builder builder) {
      super(builder);
    }
    private ServiceAccountMessage(boolean noInit) {}
    
    private static final ServiceAccountMessage defaultInstance;
    public static ServiceAccountMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ServiceAccountMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudlbs.platform.protocol.AccountProto.internal_static_account_ServiceAccountMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudlbs.platform.protocol.AccountProto.internal_static_account_ServiceAccountMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string guid = 1;
    public static final int GUID_FIELD_NUMBER = 1;
    private java.lang.Object guid_;
    public boolean hasGuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getGuid() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          guid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGuidBytes() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 createDate = 2;
    public static final int CREATEDATE_FIELD_NUMBER = 2;
    private long createDate_;
    public boolean hasCreateDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getCreateDate() {
      return createDate_;
    }
    
    // optional int64 version = 3;
    public static final int VERSION_FIELD_NUMBER = 3;
    private long version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getVersion() {
      return version_;
    }
    
    // optional string name = 4;
    public static final int NAME_FIELD_NUMBER = 4;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string description = 5;
    public static final int DESCRIPTION_FIELD_NUMBER = 5;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string status = 6;
    public static final int STATUS_FIELD_NUMBER = 6;
    private java.lang.Object status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          status_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string scopeGuid = 7;
    public static final int SCOPEGUID_FIELD_NUMBER = 7;
    private java.lang.Object scopeGuid_;
    public boolean hasScopeGuid() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getScopeGuid() {
      java.lang.Object ref = scopeGuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          scopeGuid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getScopeGuidBytes() {
      java.lang.Object ref = scopeGuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        scopeGuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string publicKey = 8;
    public static final int PUBLICKEY_FIELD_NUMBER = 8;
    private java.lang.Object publicKey_;
    public boolean hasPublicKey() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getPublicKey() {
      java.lang.Object ref = publicKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          publicKey_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPublicKeyBytes() {
      java.lang.Object ref = publicKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        publicKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string privateKey = 9;
    public static final int PRIVATEKEY_FIELD_NUMBER = 9;
    private java.lang.Object privateKey_;
    public boolean hasPrivateKey() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getPrivateKey() {
      java.lang.Object ref = privateKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          privateKey_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPrivateKeyBytes() {
      java.lang.Object ref = privateKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        privateKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string grantedAuthority = 13;
    public static final int GRANTEDAUTHORITY_FIELD_NUMBER = 13;
    private com.google.protobuf.LazyStringList grantedAuthority_;
    public java.util.List<String>
        getGrantedAuthorityList() {
      return grantedAuthority_;
    }
    public int getGrantedAuthorityCount() {
      return grantedAuthority_.size();
    }
    public String getGrantedAuthority(int index) {
      return grantedAuthority_.get(index);
    }
    
    private void initFields() {
      guid_ = "";
      createDate_ = 0L;
      version_ = 0L;
      name_ = "";
      description_ = "";
      status_ = "";
      scopeGuid_ = "";
      publicKey_ = "";
      privateKey_ = "";
      grantedAuthority_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, createDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getStatusBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getScopeGuidBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getPublicKeyBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getPrivateKeyBytes());
      }
      for (int i = 0; i < grantedAuthority_.size(); i++) {
        output.writeBytes(13, grantedAuthority_.getByteString(i));
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, createDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getStatusBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getScopeGuidBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getPublicKeyBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getPrivateKeyBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < grantedAuthority_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(grantedAuthority_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getGrantedAuthorityList().size();
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage, Builder> implements com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudlbs.platform.protocol.AccountProto.internal_static_account_ServiceAccountMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudlbs.platform.protocol.AccountProto.internal_static_account_ServiceAccountMessage_fieldAccessorTable;
      }
      
      // Construct using com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        guid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        createDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        status_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        scopeGuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        publicKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        privateKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        grantedAuthority_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage.getDescriptor();
      }
      
      public com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage getDefaultInstanceForType() {
        return com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage.getDefaultInstance();
      }
      
      public com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage build() {
        com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage buildPartial() {
        com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage result = new com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.guid_ = guid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.createDate_ = createDate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.scopeGuid_ = scopeGuid_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.publicKey_ = publicKey_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.privateKey_ = privateKey_;
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          grantedAuthority_ = new com.google.protobuf.UnmodifiableLazyStringList(
              grantedAuthority_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.grantedAuthority_ = grantedAuthority_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage) {
          return mergeFrom((com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage other) {
        if (other == com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage.getDefaultInstance()) return this;
        if (other.hasGuid()) {
          setGuid(other.getGuid());
        }
        if (other.hasCreateDate()) {
          setCreateDate(other.getCreateDate());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasScopeGuid()) {
          setScopeGuid(other.getScopeGuid());
        }
        if (other.hasPublicKey()) {
          setPublicKey(other.getPublicKey());
        }
        if (other.hasPrivateKey()) {
          setPrivateKey(other.getPrivateKey());
        }
        if (!other.grantedAuthority_.isEmpty()) {
          if (grantedAuthority_.isEmpty()) {
            grantedAuthority_ = other.grantedAuthority_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureGrantedAuthorityIsMutable();
            grantedAuthority_.addAll(other.grantedAuthority_);
          }
          onChanged();
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              guid_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              createDate_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              version_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              name_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              description_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              status_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              scopeGuid_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              publicKey_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              privateKey_ = input.readBytes();
              break;
            }
            case 106: {
              ensureGrantedAuthorityIsMutable();
              grantedAuthority_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string guid = 1;
      private java.lang.Object guid_ = "";
      public boolean hasGuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getGuid() {
        java.lang.Object ref = guid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          guid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGuid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
        return this;
      }
      public Builder clearGuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        guid_ = getDefaultInstance().getGuid();
        onChanged();
        return this;
      }
      void setGuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
      }
      
      // optional int64 createDate = 2;
      private long createDate_ ;
      public boolean hasCreateDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getCreateDate() {
        return createDate_;
      }
      public Builder setCreateDate(long value) {
        bitField0_ |= 0x00000002;
        createDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        createDate_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 version = 3;
      private long version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getVersion() {
        return version_;
      }
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string name = 4;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
      }
      
      // optional string description = 5;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000010);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        description_ = value;
        onChanged();
      }
      
      // optional string status = 6;
      private java.lang.Object status_ = "";
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStatus(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      void setStatus(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        status_ = value;
        onChanged();
      }
      
      // optional string scopeGuid = 7;
      private java.lang.Object scopeGuid_ = "";
      public boolean hasScopeGuid() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getScopeGuid() {
        java.lang.Object ref = scopeGuid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          scopeGuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setScopeGuid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        scopeGuid_ = value;
        onChanged();
        return this;
      }
      public Builder clearScopeGuid() {
        bitField0_ = (bitField0_ & ~0x00000040);
        scopeGuid_ = getDefaultInstance().getScopeGuid();
        onChanged();
        return this;
      }
      void setScopeGuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        scopeGuid_ = value;
        onChanged();
      }
      
      // optional string publicKey = 8;
      private java.lang.Object publicKey_ = "";
      public boolean hasPublicKey() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getPublicKey() {
        java.lang.Object ref = publicKey_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          publicKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPublicKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        publicKey_ = value;
        onChanged();
        return this;
      }
      public Builder clearPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000080);
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }
      void setPublicKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        publicKey_ = value;
        onChanged();
      }
      
      // optional string privateKey = 9;
      private java.lang.Object privateKey_ = "";
      public boolean hasPrivateKey() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getPrivateKey() {
        java.lang.Object ref = privateKey_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          privateKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPrivateKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        privateKey_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrivateKey() {
        bitField0_ = (bitField0_ & ~0x00000100);
        privateKey_ = getDefaultInstance().getPrivateKey();
        onChanged();
        return this;
      }
      void setPrivateKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        privateKey_ = value;
        onChanged();
      }
      
      // repeated string grantedAuthority = 13;
      private com.google.protobuf.LazyStringList grantedAuthority_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureGrantedAuthorityIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          grantedAuthority_ = new com.google.protobuf.LazyStringArrayList(grantedAuthority_);
          bitField0_ |= 0x00000200;
         }
      }
      public java.util.List<String>
          getGrantedAuthorityList() {
        return java.util.Collections.unmodifiableList(grantedAuthority_);
      }
      public int getGrantedAuthorityCount() {
        return grantedAuthority_.size();
      }
      public String getGrantedAuthority(int index) {
        return grantedAuthority_.get(index);
      }
      public Builder setGrantedAuthority(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGrantedAuthorityIsMutable();
        grantedAuthority_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addGrantedAuthority(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureGrantedAuthorityIsMutable();
        grantedAuthority_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllGrantedAuthority(
          java.lang.Iterable<String> values) {
        ensureGrantedAuthorityIsMutable();
        super.addAll(values, grantedAuthority_);
        onChanged();
        return this;
      }
      public Builder clearGrantedAuthority() {
        grantedAuthority_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      void addGrantedAuthority(com.google.protobuf.ByteString value) {
        ensureGrantedAuthorityIsMutable();
        grantedAuthority_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:account.ServiceAccountMessage)
    }
    
    static {
      defaultInstance = new ServiceAccountMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:account.ServiceAccountMessage)
    public static final int ITEMS_FIELD_NUMBER = 1001;
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.cloudlbs.platform.protocol.SearchProto.SearchResultMessage,
        java.util.List<com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage>> items = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage.getDefaultInstance(),
          0,
          com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage.class,
          com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage.getDefaultInstance());
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_account_ServiceAccountMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_ServiceAccountMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raccount.proto\022\007account\032\014search.proto\032\014" +
      "Device.proto\"\251\002\n\025ServiceAccountMessage\022\014" +
      "\n\004guid\030\001 \001(\t\022\022\n\ncreateDate\030\002 \001(\003\022\017\n\007vers" +
      "ion\030\003 \001(\003\022\014\n\004name\030\004 \001(\t\022\023\n\013description\030\005" +
      " \001(\t\022\016\n\006status\030\006 \001(\t\022\021\n\tscopeGuid\030\007 \001(\t\022" +
      "\021\n\tpublicKey\030\010 \001(\t\022\022\n\nprivateKey\030\t \001(\t\022\030" +
      "\n\020grantedAuthority\030\r \003(\t*\t\010\350\007\020\200\200\200\200\0022K\n\005i" +
      "tems\022\033.search.SearchResultMessage\030\351\007 \003(\013" +
      "2\036.account.ServiceAccountMessageB.\n\036com." +
      "cloudlbs.platform.protocolB\014AccountProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_account_ServiceAccountMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_account_ServiceAccountMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_account_ServiceAccountMessage_descriptor,
              new java.lang.String[] { "Guid", "CreateDate", "Version", "Name", "Description", "Status", "ScopeGuid", "PublicKey", "PrivateKey", "GrantedAuthority", },
              com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage.class,
              com.cloudlbs.platform.protocol.AccountProto.ServiceAccountMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cloudlbs.platform.protocol.SearchProto.getDescriptor(),
          com.cloudlbs.platform.protocol.DeviceProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
