// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ApiKey.proto

package com.cloudlbs.platform.protocol;

public final class ApiKeyProto {
  private ApiKeyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage.items);
  }
  public interface ApiKeyMessageOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<ApiKeyMessage> {
    
    // optional string guid = 1;
    boolean hasGuid();
    String getGuid();
    
    // optional int64 createDate = 2;
    boolean hasCreateDate();
    long getCreateDate();
    
    // optional int64 version = 3;
    boolean hasVersion();
    long getVersion();
    
    // optional string name = 4;
    boolean hasName();
    String getName();
    
    // optional bool usesUserAccounts = 5;
    boolean hasUsesUserAccounts();
    boolean getUsesUserAccounts();
    
    // optional string androidPackageName = 6;
    boolean hasAndroidPackageName();
    String getAndroidPackageName();
    
    // optional string iosBundleId = 7;
    boolean hasIosBundleId();
    String getIosBundleId();
    
    // optional string keyString = 8;
    boolean hasKeyString();
    String getKeyString();
    
    // optional string certFingerprint = 9;
    boolean hasCertFingerprint();
    String getCertFingerprint();
    
    // optional string platform = 10;
    boolean hasPlatform();
    String getPlatform();
    
    // optional int64 expirationDate = 11;
    boolean hasExpirationDate();
    long getExpirationDate();
    
    // optional .app.AppMessage app = 12;
    boolean hasApp();
    com.cloudlbs.platform.protocol.AppProto.AppMessage getApp();
    com.cloudlbs.platform.protocol.AppProto.AppMessageOrBuilder getAppOrBuilder();
    
    // optional string seed = 13;
    boolean hasSeed();
    String getSeed();
  }
  public static final class ApiKeyMessage extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        ApiKeyMessage> implements ApiKeyMessageOrBuilder {
    // Use ApiKeyMessage.newBuilder() to construct.
    private ApiKeyMessage(Builder builder) {
      super(builder);
    }
    private ApiKeyMessage(boolean noInit) {}
    
    private static final ApiKeyMessage defaultInstance;
    public static ApiKeyMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ApiKeyMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudlbs.platform.protocol.ApiKeyProto.internal_static_app_ApiKeyMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudlbs.platform.protocol.ApiKeyProto.internal_static_app_ApiKeyMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string guid = 1;
    public static final int GUID_FIELD_NUMBER = 1;
    private java.lang.Object guid_;
    public boolean hasGuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getGuid() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          guid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGuidBytes() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 createDate = 2;
    public static final int CREATEDATE_FIELD_NUMBER = 2;
    private long createDate_;
    public boolean hasCreateDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getCreateDate() {
      return createDate_;
    }
    
    // optional int64 version = 3;
    public static final int VERSION_FIELD_NUMBER = 3;
    private long version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getVersion() {
      return version_;
    }
    
    // optional string name = 4;
    public static final int NAME_FIELD_NUMBER = 4;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool usesUserAccounts = 5;
    public static final int USESUSERACCOUNTS_FIELD_NUMBER = 5;
    private boolean usesUserAccounts_;
    public boolean hasUsesUserAccounts() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getUsesUserAccounts() {
      return usesUserAccounts_;
    }
    
    // optional string androidPackageName = 6;
    public static final int ANDROIDPACKAGENAME_FIELD_NUMBER = 6;
    private java.lang.Object androidPackageName_;
    public boolean hasAndroidPackageName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getAndroidPackageName() {
      java.lang.Object ref = androidPackageName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          androidPackageName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAndroidPackageNameBytes() {
      java.lang.Object ref = androidPackageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        androidPackageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string iosBundleId = 7;
    public static final int IOSBUNDLEID_FIELD_NUMBER = 7;
    private java.lang.Object iosBundleId_;
    public boolean hasIosBundleId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getIosBundleId() {
      java.lang.Object ref = iosBundleId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          iosBundleId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIosBundleIdBytes() {
      java.lang.Object ref = iosBundleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        iosBundleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string keyString = 8;
    public static final int KEYSTRING_FIELD_NUMBER = 8;
    private java.lang.Object keyString_;
    public boolean hasKeyString() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getKeyString() {
      java.lang.Object ref = keyString_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          keyString_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyStringBytes() {
      java.lang.Object ref = keyString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        keyString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string certFingerprint = 9;
    public static final int CERTFINGERPRINT_FIELD_NUMBER = 9;
    private java.lang.Object certFingerprint_;
    public boolean hasCertFingerprint() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getCertFingerprint() {
      java.lang.Object ref = certFingerprint_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          certFingerprint_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCertFingerprintBytes() {
      java.lang.Object ref = certFingerprint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        certFingerprint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string platform = 10;
    public static final int PLATFORM_FIELD_NUMBER = 10;
    private java.lang.Object platform_;
    public boolean hasPlatform() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getPlatform() {
      java.lang.Object ref = platform_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          platform_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 expirationDate = 11;
    public static final int EXPIRATIONDATE_FIELD_NUMBER = 11;
    private long expirationDate_;
    public boolean hasExpirationDate() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public long getExpirationDate() {
      return expirationDate_;
    }
    
    // optional .app.AppMessage app = 12;
    public static final int APP_FIELD_NUMBER = 12;
    private com.cloudlbs.platform.protocol.AppProto.AppMessage app_;
    public boolean hasApp() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public com.cloudlbs.platform.protocol.AppProto.AppMessage getApp() {
      return app_;
    }
    public com.cloudlbs.platform.protocol.AppProto.AppMessageOrBuilder getAppOrBuilder() {
      return app_;
    }
    
    // optional string seed = 13;
    public static final int SEED_FIELD_NUMBER = 13;
    private java.lang.Object seed_;
    public boolean hasSeed() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public String getSeed() {
      java.lang.Object ref = seed_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          seed_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSeedBytes() {
      java.lang.Object ref = seed_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        seed_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      guid_ = "";
      createDate_ = 0L;
      version_ = 0L;
      name_ = "";
      usesUserAccounts_ = false;
      androidPackageName_ = "";
      iosBundleId_ = "";
      keyString_ = "";
      certFingerprint_ = "";
      platform_ = "";
      expirationDate_ = 0L;
      app_ = com.cloudlbs.platform.protocol.AppProto.AppMessage.getDefaultInstance();
      seed_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasApp()) {
        if (!getApp().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, createDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, usesUserAccounts_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getAndroidPackageNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getIosBundleIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getKeyStringBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getCertFingerprintBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getPlatformBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt64(11, expirationDate_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeMessage(12, app_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getSeedBytes());
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, createDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, usesUserAccounts_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getAndroidPackageNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getIosBundleIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getKeyStringBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getCertFingerprintBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getPlatformBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, expirationDate_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, app_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getSeedBytes());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage, Builder> implements com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudlbs.platform.protocol.ApiKeyProto.internal_static_app_ApiKeyMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudlbs.platform.protocol.ApiKeyProto.internal_static_app_ApiKeyMessage_fieldAccessorTable;
      }
      
      // Construct using com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAppFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        guid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        createDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        usesUserAccounts_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        androidPackageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        iosBundleId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        keyString_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        certFingerprint_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        platform_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        expirationDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        if (appBuilder_ == null) {
          app_ = com.cloudlbs.platform.protocol.AppProto.AppMessage.getDefaultInstance();
        } else {
          appBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000800);
        seed_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage.getDescriptor();
      }
      
      public com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage getDefaultInstanceForType() {
        return com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage.getDefaultInstance();
      }
      
      public com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage build() {
        com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage buildPartial() {
        com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage result = new com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.guid_ = guid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.createDate_ = createDate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.usesUserAccounts_ = usesUserAccounts_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.androidPackageName_ = androidPackageName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.iosBundleId_ = iosBundleId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.keyString_ = keyString_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.certFingerprint_ = certFingerprint_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.platform_ = platform_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.expirationDate_ = expirationDate_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        if (appBuilder_ == null) {
          result.app_ = app_;
        } else {
          result.app_ = appBuilder_.build();
        }
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.seed_ = seed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage) {
          return mergeFrom((com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage other) {
        if (other == com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage.getDefaultInstance()) return this;
        if (other.hasGuid()) {
          setGuid(other.getGuid());
        }
        if (other.hasCreateDate()) {
          setCreateDate(other.getCreateDate());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasUsesUserAccounts()) {
          setUsesUserAccounts(other.getUsesUserAccounts());
        }
        if (other.hasAndroidPackageName()) {
          setAndroidPackageName(other.getAndroidPackageName());
        }
        if (other.hasIosBundleId()) {
          setIosBundleId(other.getIosBundleId());
        }
        if (other.hasKeyString()) {
          setKeyString(other.getKeyString());
        }
        if (other.hasCertFingerprint()) {
          setCertFingerprint(other.getCertFingerprint());
        }
        if (other.hasPlatform()) {
          setPlatform(other.getPlatform());
        }
        if (other.hasExpirationDate()) {
          setExpirationDate(other.getExpirationDate());
        }
        if (other.hasApp()) {
          mergeApp(other.getApp());
        }
        if (other.hasSeed()) {
          setSeed(other.getSeed());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasApp()) {
          if (!getApp().isInitialized()) {
            
            return false;
          }
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              guid_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              createDate_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              version_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              name_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              usesUserAccounts_ = input.readBool();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              androidPackageName_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              iosBundleId_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              keyString_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              certFingerprint_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              platform_ = input.readBytes();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              expirationDate_ = input.readInt64();
              break;
            }
            case 98: {
              com.cloudlbs.platform.protocol.AppProto.AppMessage.Builder subBuilder = com.cloudlbs.platform.protocol.AppProto.AppMessage.newBuilder();
              if (hasApp()) {
                subBuilder.mergeFrom(getApp());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setApp(subBuilder.buildPartial());
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              seed_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string guid = 1;
      private java.lang.Object guid_ = "";
      public boolean hasGuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getGuid() {
        java.lang.Object ref = guid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          guid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGuid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
        return this;
      }
      public Builder clearGuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        guid_ = getDefaultInstance().getGuid();
        onChanged();
        return this;
      }
      void setGuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
      }
      
      // optional int64 createDate = 2;
      private long createDate_ ;
      public boolean hasCreateDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getCreateDate() {
        return createDate_;
      }
      public Builder setCreateDate(long value) {
        bitField0_ |= 0x00000002;
        createDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        createDate_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 version = 3;
      private long version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getVersion() {
        return version_;
      }
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string name = 4;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
      }
      
      // optional bool usesUserAccounts = 5;
      private boolean usesUserAccounts_ ;
      public boolean hasUsesUserAccounts() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getUsesUserAccounts() {
        return usesUserAccounts_;
      }
      public Builder setUsesUserAccounts(boolean value) {
        bitField0_ |= 0x00000010;
        usesUserAccounts_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsesUserAccounts() {
        bitField0_ = (bitField0_ & ~0x00000010);
        usesUserAccounts_ = false;
        onChanged();
        return this;
      }
      
      // optional string androidPackageName = 6;
      private java.lang.Object androidPackageName_ = "";
      public boolean hasAndroidPackageName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getAndroidPackageName() {
        java.lang.Object ref = androidPackageName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          androidPackageName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAndroidPackageName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        androidPackageName_ = value;
        onChanged();
        return this;
      }
      public Builder clearAndroidPackageName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        androidPackageName_ = getDefaultInstance().getAndroidPackageName();
        onChanged();
        return this;
      }
      void setAndroidPackageName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        androidPackageName_ = value;
        onChanged();
      }
      
      // optional string iosBundleId = 7;
      private java.lang.Object iosBundleId_ = "";
      public boolean hasIosBundleId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getIosBundleId() {
        java.lang.Object ref = iosBundleId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          iosBundleId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIosBundleId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        iosBundleId_ = value;
        onChanged();
        return this;
      }
      public Builder clearIosBundleId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        iosBundleId_ = getDefaultInstance().getIosBundleId();
        onChanged();
        return this;
      }
      void setIosBundleId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        iosBundleId_ = value;
        onChanged();
      }
      
      // optional string keyString = 8;
      private java.lang.Object keyString_ = "";
      public boolean hasKeyString() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getKeyString() {
        java.lang.Object ref = keyString_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          keyString_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKeyString(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        keyString_ = value;
        onChanged();
        return this;
      }
      public Builder clearKeyString() {
        bitField0_ = (bitField0_ & ~0x00000080);
        keyString_ = getDefaultInstance().getKeyString();
        onChanged();
        return this;
      }
      void setKeyString(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        keyString_ = value;
        onChanged();
      }
      
      // optional string certFingerprint = 9;
      private java.lang.Object certFingerprint_ = "";
      public boolean hasCertFingerprint() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getCertFingerprint() {
        java.lang.Object ref = certFingerprint_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          certFingerprint_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCertFingerprint(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        certFingerprint_ = value;
        onChanged();
        return this;
      }
      public Builder clearCertFingerprint() {
        bitField0_ = (bitField0_ & ~0x00000100);
        certFingerprint_ = getDefaultInstance().getCertFingerprint();
        onChanged();
        return this;
      }
      void setCertFingerprint(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        certFingerprint_ = value;
        onChanged();
      }
      
      // optional string platform = 10;
      private java.lang.Object platform_ = "";
      public boolean hasPlatform() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getPlatform() {
        java.lang.Object ref = platform_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          platform_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPlatform(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        platform_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlatform() {
        bitField0_ = (bitField0_ & ~0x00000200);
        platform_ = getDefaultInstance().getPlatform();
        onChanged();
        return this;
      }
      void setPlatform(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        platform_ = value;
        onChanged();
      }
      
      // optional int64 expirationDate = 11;
      private long expirationDate_ ;
      public boolean hasExpirationDate() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public long getExpirationDate() {
        return expirationDate_;
      }
      public Builder setExpirationDate(long value) {
        bitField0_ |= 0x00000400;
        expirationDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearExpirationDate() {
        bitField0_ = (bitField0_ & ~0x00000400);
        expirationDate_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .app.AppMessage app = 12;
      private com.cloudlbs.platform.protocol.AppProto.AppMessage app_ = com.cloudlbs.platform.protocol.AppProto.AppMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.cloudlbs.platform.protocol.AppProto.AppMessage, com.cloudlbs.platform.protocol.AppProto.AppMessage.Builder, com.cloudlbs.platform.protocol.AppProto.AppMessageOrBuilder> appBuilder_;
      public boolean hasApp() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public com.cloudlbs.platform.protocol.AppProto.AppMessage getApp() {
        if (appBuilder_ == null) {
          return app_;
        } else {
          return appBuilder_.getMessage();
        }
      }
      public Builder setApp(com.cloudlbs.platform.protocol.AppProto.AppMessage value) {
        if (appBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          app_ = value;
          onChanged();
        } else {
          appBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      public Builder setApp(
          com.cloudlbs.platform.protocol.AppProto.AppMessage.Builder builderForValue) {
        if (appBuilder_ == null) {
          app_ = builderForValue.build();
          onChanged();
        } else {
          appBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      public Builder mergeApp(com.cloudlbs.platform.protocol.AppProto.AppMessage value) {
        if (appBuilder_ == null) {
          if (((bitField0_ & 0x00000800) == 0x00000800) &&
              app_ != com.cloudlbs.platform.protocol.AppProto.AppMessage.getDefaultInstance()) {
            app_ =
              com.cloudlbs.platform.protocol.AppProto.AppMessage.newBuilder(app_).mergeFrom(value).buildPartial();
          } else {
            app_ = value;
          }
          onChanged();
        } else {
          appBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000800;
        return this;
      }
      public Builder clearApp() {
        if (appBuilder_ == null) {
          app_ = com.cloudlbs.platform.protocol.AppProto.AppMessage.getDefaultInstance();
          onChanged();
        } else {
          appBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }
      public com.cloudlbs.platform.protocol.AppProto.AppMessage.Builder getAppBuilder() {
        bitField0_ |= 0x00000800;
        onChanged();
        return getAppFieldBuilder().getBuilder();
      }
      public com.cloudlbs.platform.protocol.AppProto.AppMessageOrBuilder getAppOrBuilder() {
        if (appBuilder_ != null) {
          return appBuilder_.getMessageOrBuilder();
        } else {
          return app_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.cloudlbs.platform.protocol.AppProto.AppMessage, com.cloudlbs.platform.protocol.AppProto.AppMessage.Builder, com.cloudlbs.platform.protocol.AppProto.AppMessageOrBuilder> 
          getAppFieldBuilder() {
        if (appBuilder_ == null) {
          appBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.cloudlbs.platform.protocol.AppProto.AppMessage, com.cloudlbs.platform.protocol.AppProto.AppMessage.Builder, com.cloudlbs.platform.protocol.AppProto.AppMessageOrBuilder>(
                  app_,
                  getParentForChildren(),
                  isClean());
          app_ = null;
        }
        return appBuilder_;
      }
      
      // optional string seed = 13;
      private java.lang.Object seed_ = "";
      public boolean hasSeed() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public String getSeed() {
        java.lang.Object ref = seed_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          seed_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSeed(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        seed_ = value;
        onChanged();
        return this;
      }
      public Builder clearSeed() {
        bitField0_ = (bitField0_ & ~0x00001000);
        seed_ = getDefaultInstance().getSeed();
        onChanged();
        return this;
      }
      void setSeed(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00001000;
        seed_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:app.ApiKeyMessage)
    }
    
    static {
      defaultInstance = new ApiKeyMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:app.ApiKeyMessage)
    public static final int ITEMS_FIELD_NUMBER = 1010;
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.cloudlbs.platform.protocol.SearchProto.SearchResultMessage,
        java.util.List<com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage>> items = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage.getDefaultInstance(),
          0,
          com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage.class,
          com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage.getDefaultInstance());
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_app_ApiKeyMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_app_ApiKeyMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014ApiKey.proto\022\003app\032\tApp.proto\032\014search.p" +
      "roto\"\351\002\n\rApiKeyMessage\022\014\n\004guid\030\001 \001(\t\022\022\n\n" +
      "createDate\030\002 \001(\003\022\017\n\007version\030\003 \001(\003\022\014\n\004nam" +
      "e\030\004 \001(\t\022\030\n\020usesUserAccounts\030\005 \001(\010\022\032\n\022and" +
      "roidPackageName\030\006 \001(\t\022\023\n\013iosBundleId\030\007 \001" +
      "(\t\022\021\n\tkeyString\030\010 \001(\t\022\027\n\017certFingerprint" +
      "\030\t \001(\t\022\020\n\010platform\030\n \001(\t\022\026\n\016expirationDa" +
      "te\030\013 \001(\003\022\034\n\003app\030\014 \001(\0132\017.app.AppMessage\022\014" +
      "\n\004seed\030\r \001(\t*\t\010\350\007\020\200\200\200\200\0022?\n\005items\022\033.searc" +
      "h.SearchResultMessage\030\362\007 \003(\0132\022.app.ApiKe",
      "yMessageB-\n\036com.cloudlbs.platform.protoc" +
      "olB\013ApiKeyProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_app_ApiKeyMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_app_ApiKeyMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_app_ApiKeyMessage_descriptor,
              new java.lang.String[] { "Guid", "CreateDate", "Version", "Name", "UsesUserAccounts", "AndroidPackageName", "IosBundleId", "KeyString", "CertFingerprint", "Platform", "ExpirationDate", "App", "Seed", },
              com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage.class,
              com.cloudlbs.platform.protocol.ApiKeyProto.ApiKeyMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cloudlbs.platform.protocol.AppProto.getDescriptor(),
          com.cloudlbs.platform.protocol.SearchProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
