// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: App.proto

package com.cloudlbs.platform.protocol;

public final class AppProto {
  private AppProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.cloudlbs.platform.protocol.AppProto.AppMessage.items);
  }
  public interface AppMessageOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<AppMessage> {
    
    // optional string guid = 1;
    boolean hasGuid();
    String getGuid();
    
    // optional int64 createDate = 2;
    boolean hasCreateDate();
    long getCreateDate();
    
    // optional int64 version = 3;
    boolean hasVersion();
    long getVersion();
    
    // optional string name = 4;
    boolean hasName();
    String getName();
    
    // optional bool usesUserAccounts = 5;
    boolean hasUsesUserAccounts();
    boolean getUsesUserAccounts();
    
    // optional string androidPackageName = 6;
    boolean hasAndroidPackageName();
    String getAndroidPackageName();
    
    // optional string iosBundleId = 7;
    boolean hasIosBundleId();
    String getIosBundleId();
  }
  public static final class AppMessage extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        AppMessage> implements AppMessageOrBuilder {
    // Use AppMessage.newBuilder() to construct.
    private AppMessage(Builder builder) {
      super(builder);
    }
    private AppMessage(boolean noInit) {}
    
    private static final AppMessage defaultInstance;
    public static AppMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public AppMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudlbs.platform.protocol.AppProto.internal_static_app_AppMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudlbs.platform.protocol.AppProto.internal_static_app_AppMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string guid = 1;
    public static final int GUID_FIELD_NUMBER = 1;
    private java.lang.Object guid_;
    public boolean hasGuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getGuid() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          guid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGuidBytes() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 createDate = 2;
    public static final int CREATEDATE_FIELD_NUMBER = 2;
    private long createDate_;
    public boolean hasCreateDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getCreateDate() {
      return createDate_;
    }
    
    // optional int64 version = 3;
    public static final int VERSION_FIELD_NUMBER = 3;
    private long version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getVersion() {
      return version_;
    }
    
    // optional string name = 4;
    public static final int NAME_FIELD_NUMBER = 4;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool usesUserAccounts = 5;
    public static final int USESUSERACCOUNTS_FIELD_NUMBER = 5;
    private boolean usesUserAccounts_;
    public boolean hasUsesUserAccounts() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getUsesUserAccounts() {
      return usesUserAccounts_;
    }
    
    // optional string androidPackageName = 6;
    public static final int ANDROIDPACKAGENAME_FIELD_NUMBER = 6;
    private java.lang.Object androidPackageName_;
    public boolean hasAndroidPackageName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getAndroidPackageName() {
      java.lang.Object ref = androidPackageName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          androidPackageName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAndroidPackageNameBytes() {
      java.lang.Object ref = androidPackageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        androidPackageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string iosBundleId = 7;
    public static final int IOSBUNDLEID_FIELD_NUMBER = 7;
    private java.lang.Object iosBundleId_;
    public boolean hasIosBundleId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getIosBundleId() {
      java.lang.Object ref = iosBundleId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          iosBundleId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIosBundleIdBytes() {
      java.lang.Object ref = iosBundleId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        iosBundleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      guid_ = "";
      createDate_ = 0L;
      version_ = 0L;
      name_ = "";
      usesUserAccounts_ = false;
      androidPackageName_ = "";
      iosBundleId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.cloudlbs.platform.protocol.AppProto.AppMessage>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, createDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, usesUserAccounts_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getAndroidPackageNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getIosBundleIdBytes());
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, createDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, usesUserAccounts_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getAndroidPackageNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getIosBundleIdBytes());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cloudlbs.platform.protocol.AppProto.AppMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AppProto.AppMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AppProto.AppMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AppProto.AppMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AppProto.AppMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AppProto.AppMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AppProto.AppMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.AppProto.AppMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.AppProto.AppMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.AppProto.AppMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudlbs.platform.protocol.AppProto.AppMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.cloudlbs.platform.protocol.AppProto.AppMessage, Builder> implements com.cloudlbs.platform.protocol.AppProto.AppMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudlbs.platform.protocol.AppProto.internal_static_app_AppMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudlbs.platform.protocol.AppProto.internal_static_app_AppMessage_fieldAccessorTable;
      }
      
      // Construct using com.cloudlbs.platform.protocol.AppProto.AppMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        guid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        createDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        usesUserAccounts_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        androidPackageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        iosBundleId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudlbs.platform.protocol.AppProto.AppMessage.getDescriptor();
      }
      
      public com.cloudlbs.platform.protocol.AppProto.AppMessage getDefaultInstanceForType() {
        return com.cloudlbs.platform.protocol.AppProto.AppMessage.getDefaultInstance();
      }
      
      public com.cloudlbs.platform.protocol.AppProto.AppMessage build() {
        com.cloudlbs.platform.protocol.AppProto.AppMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cloudlbs.platform.protocol.AppProto.AppMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cloudlbs.platform.protocol.AppProto.AppMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cloudlbs.platform.protocol.AppProto.AppMessage buildPartial() {
        com.cloudlbs.platform.protocol.AppProto.AppMessage result = new com.cloudlbs.platform.protocol.AppProto.AppMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.guid_ = guid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.createDate_ = createDate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.usesUserAccounts_ = usesUserAccounts_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.androidPackageName_ = androidPackageName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.iosBundleId_ = iosBundleId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudlbs.platform.protocol.AppProto.AppMessage) {
          return mergeFrom((com.cloudlbs.platform.protocol.AppProto.AppMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cloudlbs.platform.protocol.AppProto.AppMessage other) {
        if (other == com.cloudlbs.platform.protocol.AppProto.AppMessage.getDefaultInstance()) return this;
        if (other.hasGuid()) {
          setGuid(other.getGuid());
        }
        if (other.hasCreateDate()) {
          setCreateDate(other.getCreateDate());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasUsesUserAccounts()) {
          setUsesUserAccounts(other.getUsesUserAccounts());
        }
        if (other.hasAndroidPackageName()) {
          setAndroidPackageName(other.getAndroidPackageName());
        }
        if (other.hasIosBundleId()) {
          setIosBundleId(other.getIosBundleId());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              guid_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              createDate_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              version_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              name_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              usesUserAccounts_ = input.readBool();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              androidPackageName_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              iosBundleId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string guid = 1;
      private java.lang.Object guid_ = "";
      public boolean hasGuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getGuid() {
        java.lang.Object ref = guid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          guid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGuid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
        return this;
      }
      public Builder clearGuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        guid_ = getDefaultInstance().getGuid();
        onChanged();
        return this;
      }
      void setGuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
      }
      
      // optional int64 createDate = 2;
      private long createDate_ ;
      public boolean hasCreateDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getCreateDate() {
        return createDate_;
      }
      public Builder setCreateDate(long value) {
        bitField0_ |= 0x00000002;
        createDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        createDate_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 version = 3;
      private long version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getVersion() {
        return version_;
      }
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string name = 4;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        name_ = value;
        onChanged();
      }
      
      // optional bool usesUserAccounts = 5;
      private boolean usesUserAccounts_ ;
      public boolean hasUsesUserAccounts() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getUsesUserAccounts() {
        return usesUserAccounts_;
      }
      public Builder setUsesUserAccounts(boolean value) {
        bitField0_ |= 0x00000010;
        usesUserAccounts_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsesUserAccounts() {
        bitField0_ = (bitField0_ & ~0x00000010);
        usesUserAccounts_ = false;
        onChanged();
        return this;
      }
      
      // optional string androidPackageName = 6;
      private java.lang.Object androidPackageName_ = "";
      public boolean hasAndroidPackageName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getAndroidPackageName() {
        java.lang.Object ref = androidPackageName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          androidPackageName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAndroidPackageName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        androidPackageName_ = value;
        onChanged();
        return this;
      }
      public Builder clearAndroidPackageName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        androidPackageName_ = getDefaultInstance().getAndroidPackageName();
        onChanged();
        return this;
      }
      void setAndroidPackageName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        androidPackageName_ = value;
        onChanged();
      }
      
      // optional string iosBundleId = 7;
      private java.lang.Object iosBundleId_ = "";
      public boolean hasIosBundleId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getIosBundleId() {
        java.lang.Object ref = iosBundleId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          iosBundleId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIosBundleId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        iosBundleId_ = value;
        onChanged();
        return this;
      }
      public Builder clearIosBundleId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        iosBundleId_ = getDefaultInstance().getIosBundleId();
        onChanged();
        return this;
      }
      void setIosBundleId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        iosBundleId_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:app.AppMessage)
    }
    
    static {
      defaultInstance = new AppMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:app.AppMessage)
    public static final int ITEMS_FIELD_NUMBER = 1009;
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.cloudlbs.platform.protocol.SearchProto.SearchResultMessage,
        java.util.List<com.cloudlbs.platform.protocol.AppProto.AppMessage>> items = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.cloudlbs.platform.protocol.AppProto.AppMessage.getDefaultInstance(),
          0,
          com.cloudlbs.platform.protocol.AppProto.AppMessage.class,
          com.cloudlbs.platform.protocol.AppProto.AppMessage.getDefaultInstance());
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_app_AppMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_app_AppMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tApp.proto\022\003app\032\014search.proto\"\341\001\n\nAppMe" +
      "ssage\022\014\n\004guid\030\001 \001(\t\022\022\n\ncreateDate\030\002 \001(\003\022" +
      "\017\n\007version\030\003 \001(\003\022\014\n\004name\030\004 \001(\t\022\030\n\020usesUs" +
      "erAccounts\030\005 \001(\010\022\032\n\022androidPackageName\030\006" +
      " \001(\t\022\023\n\013iosBundleId\030\007 \001(\t*\t\010\350\007\020\200\200\200\200\0022<\n\005" +
      "items\022\033.search.SearchResultMessage\030\361\007 \003(" +
      "\0132\017.app.AppMessageB*\n\036com.cloudlbs.platf" +
      "orm.protocolB\010AppProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_app_AppMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_app_AppMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_app_AppMessage_descriptor,
              new java.lang.String[] { "Guid", "CreateDate", "Version", "Name", "UsesUserAccounts", "AndroidPackageName", "IosBundleId", },
              com.cloudlbs.platform.protocol.AppProto.AppMessage.class,
              com.cloudlbs.platform.protocol.AppProto.AppMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cloudlbs.platform.protocol.SearchProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
