// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Device.proto

package com.cloudlbs.platform.protocol;

public final class DeviceProto {
  private DeviceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage.items);
  }
  public interface DeviceMessageOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<DeviceMessage> {
    
    // optional string guid = 1;
    boolean hasGuid();
    String getGuid();
    
    // optional int64 createDate = 2;
    boolean hasCreateDate();
    long getCreateDate();
    
    // optional int64 version = 3;
    boolean hasVersion();
    long getVersion();
    
    // optional string deviceUniqueId = 4;
    boolean hasDeviceUniqueId();
    String getDeviceUniqueId();
    
    // optional string xmppUsername = 6;
    boolean hasXmppUsername();
    String getXmppUsername();
    
    // optional string xmppPassword = 7;
    boolean hasXmppPassword();
    String getXmppPassword();
  }
  public static final class DeviceMessage extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        DeviceMessage> implements DeviceMessageOrBuilder {
    // Use DeviceMessage.newBuilder() to construct.
    private DeviceMessage(Builder builder) {
      super(builder);
    }
    private DeviceMessage(boolean noInit) {}
    
    private static final DeviceMessage defaultInstance;
    public static DeviceMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public DeviceMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudlbs.platform.protocol.DeviceProto.internal_static_device_DeviceMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudlbs.platform.protocol.DeviceProto.internal_static_device_DeviceMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string guid = 1;
    public static final int GUID_FIELD_NUMBER = 1;
    private java.lang.Object guid_;
    public boolean hasGuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getGuid() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          guid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGuidBytes() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 createDate = 2;
    public static final int CREATEDATE_FIELD_NUMBER = 2;
    private long createDate_;
    public boolean hasCreateDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getCreateDate() {
      return createDate_;
    }
    
    // optional int64 version = 3;
    public static final int VERSION_FIELD_NUMBER = 3;
    private long version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getVersion() {
      return version_;
    }
    
    // optional string deviceUniqueId = 4;
    public static final int DEVICEUNIQUEID_FIELD_NUMBER = 4;
    private java.lang.Object deviceUniqueId_;
    public boolean hasDeviceUniqueId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDeviceUniqueId() {
      java.lang.Object ref = deviceUniqueId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceUniqueId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceUniqueIdBytes() {
      java.lang.Object ref = deviceUniqueId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        deviceUniqueId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string xmppUsername = 6;
    public static final int XMPPUSERNAME_FIELD_NUMBER = 6;
    private java.lang.Object xmppUsername_;
    public boolean hasXmppUsername() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getXmppUsername() {
      java.lang.Object ref = xmppUsername_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          xmppUsername_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getXmppUsernameBytes() {
      java.lang.Object ref = xmppUsername_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        xmppUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string xmppPassword = 7;
    public static final int XMPPPASSWORD_FIELD_NUMBER = 7;
    private java.lang.Object xmppPassword_;
    public boolean hasXmppPassword() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getXmppPassword() {
      java.lang.Object ref = xmppPassword_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          xmppPassword_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getXmppPasswordBytes() {
      java.lang.Object ref = xmppPassword_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        xmppPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      guid_ = "";
      createDate_ = 0L;
      version_ = 0L;
      deviceUniqueId_ = "";
      xmppUsername_ = "";
      xmppPassword_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, createDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDeviceUniqueIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getXmppUsernameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(7, getXmppPasswordBytes());
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, createDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDeviceUniqueIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getXmppUsernameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getXmppPasswordBytes());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage, Builder> implements com.cloudlbs.platform.protocol.DeviceProto.DeviceMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudlbs.platform.protocol.DeviceProto.internal_static_device_DeviceMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudlbs.platform.protocol.DeviceProto.internal_static_device_DeviceMessage_fieldAccessorTable;
      }
      
      // Construct using com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        guid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        createDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceUniqueId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        xmppUsername_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        xmppPassword_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage.getDescriptor();
      }
      
      public com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage getDefaultInstanceForType() {
        return com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage.getDefaultInstance();
      }
      
      public com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage build() {
        com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage buildPartial() {
        com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage result = new com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.guid_ = guid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.createDate_ = createDate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deviceUniqueId_ = deviceUniqueId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.xmppUsername_ = xmppUsername_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.xmppPassword_ = xmppPassword_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage) {
          return mergeFrom((com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage other) {
        if (other == com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage.getDefaultInstance()) return this;
        if (other.hasGuid()) {
          setGuid(other.getGuid());
        }
        if (other.hasCreateDate()) {
          setCreateDate(other.getCreateDate());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasDeviceUniqueId()) {
          setDeviceUniqueId(other.getDeviceUniqueId());
        }
        if (other.hasXmppUsername()) {
          setXmppUsername(other.getXmppUsername());
        }
        if (other.hasXmppPassword()) {
          setXmppPassword(other.getXmppPassword());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              guid_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              createDate_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              version_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              deviceUniqueId_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              xmppUsername_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000020;
              xmppPassword_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string guid = 1;
      private java.lang.Object guid_ = "";
      public boolean hasGuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getGuid() {
        java.lang.Object ref = guid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          guid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGuid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
        return this;
      }
      public Builder clearGuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        guid_ = getDefaultInstance().getGuid();
        onChanged();
        return this;
      }
      void setGuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
      }
      
      // optional int64 createDate = 2;
      private long createDate_ ;
      public boolean hasCreateDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getCreateDate() {
        return createDate_;
      }
      public Builder setCreateDate(long value) {
        bitField0_ |= 0x00000002;
        createDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        createDate_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 version = 3;
      private long version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getVersion() {
        return version_;
      }
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string deviceUniqueId = 4;
      private java.lang.Object deviceUniqueId_ = "";
      public boolean hasDeviceUniqueId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getDeviceUniqueId() {
        java.lang.Object ref = deviceUniqueId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          deviceUniqueId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceUniqueId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceUniqueId_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceUniqueId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceUniqueId_ = getDefaultInstance().getDeviceUniqueId();
        onChanged();
        return this;
      }
      void setDeviceUniqueId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        deviceUniqueId_ = value;
        onChanged();
      }
      
      // optional string xmppUsername = 6;
      private java.lang.Object xmppUsername_ = "";
      public boolean hasXmppUsername() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getXmppUsername() {
        java.lang.Object ref = xmppUsername_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          xmppUsername_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setXmppUsername(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        xmppUsername_ = value;
        onChanged();
        return this;
      }
      public Builder clearXmppUsername() {
        bitField0_ = (bitField0_ & ~0x00000010);
        xmppUsername_ = getDefaultInstance().getXmppUsername();
        onChanged();
        return this;
      }
      void setXmppUsername(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        xmppUsername_ = value;
        onChanged();
      }
      
      // optional string xmppPassword = 7;
      private java.lang.Object xmppPassword_ = "";
      public boolean hasXmppPassword() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getXmppPassword() {
        java.lang.Object ref = xmppPassword_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          xmppPassword_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setXmppPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        xmppPassword_ = value;
        onChanged();
        return this;
      }
      public Builder clearXmppPassword() {
        bitField0_ = (bitField0_ & ~0x00000020);
        xmppPassword_ = getDefaultInstance().getXmppPassword();
        onChanged();
        return this;
      }
      void setXmppPassword(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        xmppPassword_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:device.DeviceMessage)
    }
    
    static {
      defaultInstance = new DeviceMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:device.DeviceMessage)
    public static final int ITEMS_FIELD_NUMBER = 1008;
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.cloudlbs.platform.protocol.SearchProto.SearchResultMessage,
        java.util.List<com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage>> items = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage.getDefaultInstance(),
          0,
          com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage.class,
          com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage.getDefaultInstance());
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_device_DeviceMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_device_DeviceMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Device.proto\022\006device\032\014search.proto\"\325\001\n" +
      "\rDeviceMessage\022\014\n\004guid\030\001 \001(\t\022\022\n\ncreateDa" +
      "te\030\002 \001(\003\022\017\n\007version\030\003 \001(\003\022\026\n\016deviceUniqu" +
      "eId\030\004 \001(\t\022\024\n\014xmppUsername\030\006 \001(\t\022\024\n\014xmppP" +
      "assword\030\007 \001(\t*\t\010\350\007\020\200\200\200\200\0022B\n\005items\022\033.sear" +
      "ch.SearchResultMessage\030\360\007 \003(\0132\025.device.D" +
      "eviceMessageB-\n\036com.cloudlbs.platform.pr" +
      "otocolB\013DeviceProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_device_DeviceMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_device_DeviceMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_device_DeviceMessage_descriptor,
              new java.lang.String[] { "Guid", "CreateDate", "Version", "DeviceUniqueId", "XmppUsername", "XmppPassword", },
              com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage.class,
              com.cloudlbs.platform.protocol.DeviceProto.DeviceMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cloudlbs.platform.protocol.SearchProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
