// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scope.proto

package com.cloudlbs.platform.protocol;

public final class ScopeProto {
  private ScopeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.items);
  }
  public interface ScopeMessageOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<ScopeMessage> {
    
    // optional string guid = 1;
    boolean hasGuid();
    String getGuid();
    
    // optional .scope.ScopeMessage parent = 2;
    boolean hasParent();
    com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage getParent();
    com.cloudlbs.platform.protocol.ScopeProto.ScopeMessageOrBuilder getParentOrBuilder();
    
    // optional string label = 3;
    boolean hasLabel();
    String getLabel();
    
    // optional int64 createDate = 4;
    boolean hasCreateDate();
    long getCreateDate();
    
    // optional int64 version = 5;
    boolean hasVersion();
    long getVersion();
  }
  public static final class ScopeMessage extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        ScopeMessage> implements ScopeMessageOrBuilder {
    // Use ScopeMessage.newBuilder() to construct.
    private ScopeMessage(Builder builder) {
      super(builder);
    }
    private ScopeMessage(boolean noInit) {}
    
    private static final ScopeMessage defaultInstance;
    public static ScopeMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ScopeMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudlbs.platform.protocol.ScopeProto.internal_static_scope_ScopeMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudlbs.platform.protocol.ScopeProto.internal_static_scope_ScopeMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string guid = 1;
    public static final int GUID_FIELD_NUMBER = 1;
    private java.lang.Object guid_;
    public boolean hasGuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getGuid() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          guid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGuidBytes() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .scope.ScopeMessage parent = 2;
    public static final int PARENT_FIELD_NUMBER = 2;
    private com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage parent_;
    public boolean hasParent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage getParent() {
      return parent_;
    }
    public com.cloudlbs.platform.protocol.ScopeProto.ScopeMessageOrBuilder getParentOrBuilder() {
      return parent_;
    }
    
    // optional string label = 3;
    public static final int LABEL_FIELD_NUMBER = 3;
    private java.lang.Object label_;
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          label_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 createDate = 4;
    public static final int CREATEDATE_FIELD_NUMBER = 4;
    private long createDate_;
    public boolean hasCreateDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getCreateDate() {
      return createDate_;
    }
    
    // optional int64 version = 5;
    public static final int VERSION_FIELD_NUMBER = 5;
    private long version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getVersion() {
      return version_;
    }
    
    private void initFields() {
      guid_ = "";
      parent_ = com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.getDefaultInstance();
      label_ = "";
      createDate_ = 0L;
      version_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasParent()) {
        if (!getParent().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, parent_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLabelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, createDate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, version_);
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, parent_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLabelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, createDate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, version_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage, Builder> implements com.cloudlbs.platform.protocol.ScopeProto.ScopeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudlbs.platform.protocol.ScopeProto.internal_static_scope_ScopeMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudlbs.platform.protocol.ScopeProto.internal_static_scope_ScopeMessage_fieldAccessorTable;
      }
      
      // Construct using com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getParentFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        guid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (parentBuilder_ == null) {
          parent_ = com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.getDefaultInstance();
        } else {
          parentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        createDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.getDescriptor();
      }
      
      public com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage getDefaultInstanceForType() {
        return com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.getDefaultInstance();
      }
      
      public com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage build() {
        com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage buildPartial() {
        com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage result = new com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.guid_ = guid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (parentBuilder_ == null) {
          result.parent_ = parent_;
        } else {
          result.parent_ = parentBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.label_ = label_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createDate_ = createDate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.version_ = version_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage) {
          return mergeFrom((com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage other) {
        if (other == com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.getDefaultInstance()) return this;
        if (other.hasGuid()) {
          setGuid(other.getGuid());
        }
        if (other.hasParent()) {
          mergeParent(other.getParent());
        }
        if (other.hasLabel()) {
          setLabel(other.getLabel());
        }
        if (other.hasCreateDate()) {
          setCreateDate(other.getCreateDate());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasParent()) {
          if (!getParent().isInitialized()) {
            
            return false;
          }
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              guid_ = input.readBytes();
              break;
            }
            case 18: {
              com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.Builder subBuilder = com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.newBuilder();
              if (hasParent()) {
                subBuilder.mergeFrom(getParent());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setParent(subBuilder.buildPartial());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              label_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              createDate_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              version_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string guid = 1;
      private java.lang.Object guid_ = "";
      public boolean hasGuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getGuid() {
        java.lang.Object ref = guid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          guid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGuid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
        return this;
      }
      public Builder clearGuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        guid_ = getDefaultInstance().getGuid();
        onChanged();
        return this;
      }
      void setGuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
      }
      
      // optional .scope.ScopeMessage parent = 2;
      private com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage parent_ = com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage, com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.Builder, com.cloudlbs.platform.protocol.ScopeProto.ScopeMessageOrBuilder> parentBuilder_;
      public boolean hasParent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage getParent() {
        if (parentBuilder_ == null) {
          return parent_;
        } else {
          return parentBuilder_.getMessage();
        }
      }
      public Builder setParent(com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage value) {
        if (parentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          parent_ = value;
          onChanged();
        } else {
          parentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setParent(
          com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.Builder builderForValue) {
        if (parentBuilder_ == null) {
          parent_ = builderForValue.build();
          onChanged();
        } else {
          parentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeParent(com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage value) {
        if (parentBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              parent_ != com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.getDefaultInstance()) {
            parent_ =
              com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.newBuilder(parent_).mergeFrom(value).buildPartial();
          } else {
            parent_ = value;
          }
          onChanged();
        } else {
          parentBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearParent() {
        if (parentBuilder_ == null) {
          parent_ = com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.getDefaultInstance();
          onChanged();
        } else {
          parentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.Builder getParentBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getParentFieldBuilder().getBuilder();
      }
      public com.cloudlbs.platform.protocol.ScopeProto.ScopeMessageOrBuilder getParentOrBuilder() {
        if (parentBuilder_ != null) {
          return parentBuilder_.getMessageOrBuilder();
        } else {
          return parent_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage, com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.Builder, com.cloudlbs.platform.protocol.ScopeProto.ScopeMessageOrBuilder> 
          getParentFieldBuilder() {
        if (parentBuilder_ == null) {
          parentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage, com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.Builder, com.cloudlbs.platform.protocol.ScopeProto.ScopeMessageOrBuilder>(
                  parent_,
                  getParentForChildren(),
                  isClean());
          parent_ = null;
        }
        return parentBuilder_;
      }
      
      // optional string label = 3;
      private java.lang.Object label_ = "";
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLabel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        label_ = value;
        onChanged();
        return this;
      }
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      void setLabel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        label_ = value;
        onChanged();
      }
      
      // optional int64 createDate = 4;
      private long createDate_ ;
      public boolean hasCreateDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getCreateDate() {
        return createDate_;
      }
      public Builder setCreateDate(long value) {
        bitField0_ |= 0x00000008;
        createDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createDate_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 version = 5;
      private long version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getVersion() {
        return version_;
      }
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000010;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000010);
        version_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:scope.ScopeMessage)
    }
    
    static {
      defaultInstance = new ScopeMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:scope.ScopeMessage)
    public static final int ITEMS_FIELD_NUMBER = 1006;
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.cloudlbs.platform.protocol.SearchProto.SearchResultMessage,
        java.util.List<com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage>> items = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.getDefaultInstance(),
          0,
          com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.class,
          com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.getDefaultInstance());
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scope_ScopeMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scope_ScopeMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013scope.proto\022\005scope\032\014search.proto\"\302\001\n\014S" +
      "copeMessage\022\014\n\004guid\030\001 \001(\t\022#\n\006parent\030\002 \001(" +
      "\0132\023.scope.ScopeMessage\022\r\n\005label\030\003 \001(\t\022\022\n" +
      "\ncreateDate\030\004 \001(\003\022\017\n\007version\030\005 \001(\003*\t\010\350\007\020" +
      "\200\200\200\200\0022@\n\005items\022\033.search.SearchResultMess" +
      "age\030\356\007 \003(\0132\023.scope.ScopeMessageB,\n\036com.c" +
      "loudlbs.platform.protocolB\nScopeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_scope_ScopeMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_scope_ScopeMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scope_ScopeMessage_descriptor,
              new java.lang.String[] { "Guid", "Parent", "Label", "CreateDate", "Version", },
              com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.class,
              com.cloudlbs.platform.protocol.ScopeProto.ScopeMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cloudlbs.platform.protocol.SearchProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
