// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserAccount.proto

package com.cloudlbs.platform.protocol;

public final class UserAccountProto {
  private UserAccountProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage.items);
  }
  public interface UserAccountMessageOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<UserAccountMessage> {
    
    // optional string guid = 1;
    boolean hasGuid();
    String getGuid();
    
    // optional int64 createDate = 2;
    boolean hasCreateDate();
    long getCreateDate();
    
    // optional int64 version = 3;
    boolean hasVersion();
    long getVersion();
    
    // optional string email = 4;
    boolean hasEmail();
    String getEmail();
    
    // optional string status = 5;
    boolean hasStatus();
    String getStatus();
    
    // optional string firstName = 7;
    boolean hasFirstName();
    String getFirstName();
    
    // optional string lastName = 8;
    boolean hasLastName();
    String getLastName();
    
    // optional string password = 9;
    boolean hasPassword();
    String getPassword();
    
    // repeated .account.RoleMessage grantedAuthority = 10;
    java.util.List<com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage> 
        getGrantedAuthorityList();
    com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage getGrantedAuthority(int index);
    int getGrantedAuthorityCount();
    java.util.List<? extends com.cloudlbs.platform.protocol.UserAccountProto.RoleMessageOrBuilder> 
        getGrantedAuthorityOrBuilderList();
    com.cloudlbs.platform.protocol.UserAccountProto.RoleMessageOrBuilder getGrantedAuthorityOrBuilder(
        int index);
    
    // optional string username = 11;
    boolean hasUsername();
    String getUsername();
    
    // optional string displayName = 12;
    boolean hasDisplayName();
    String getDisplayName();
  }
  public static final class UserAccountMessage extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        UserAccountMessage> implements UserAccountMessageOrBuilder {
    // Use UserAccountMessage.newBuilder() to construct.
    private UserAccountMessage(Builder builder) {
      super(builder);
    }
    private UserAccountMessage(boolean noInit) {}
    
    private static final UserAccountMessage defaultInstance;
    public static UserAccountMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserAccountMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudlbs.platform.protocol.UserAccountProto.internal_static_account_UserAccountMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudlbs.platform.protocol.UserAccountProto.internal_static_account_UserAccountMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string guid = 1;
    public static final int GUID_FIELD_NUMBER = 1;
    private java.lang.Object guid_;
    public boolean hasGuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getGuid() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          guid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGuidBytes() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 createDate = 2;
    public static final int CREATEDATE_FIELD_NUMBER = 2;
    private long createDate_;
    public boolean hasCreateDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getCreateDate() {
      return createDate_;
    }
    
    // optional int64 version = 3;
    public static final int VERSION_FIELD_NUMBER = 3;
    private long version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getVersion() {
      return version_;
    }
    
    // optional string email = 4;
    public static final int EMAIL_FIELD_NUMBER = 4;
    private java.lang.Object email_;
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          email_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string status = 5;
    public static final int STATUS_FIELD_NUMBER = 5;
    private java.lang.Object status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          status_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string firstName = 7;
    public static final int FIRSTNAME_FIELD_NUMBER = 7;
    private java.lang.Object firstName_;
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          firstName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string lastName = 8;
    public static final int LASTNAME_FIELD_NUMBER = 8;
    private java.lang.Object lastName_;
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          lastName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string password = 9;
    public static final int PASSWORD_FIELD_NUMBER = 9;
    private java.lang.Object password_;
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          password_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .account.RoleMessage grantedAuthority = 10;
    public static final int GRANTEDAUTHORITY_FIELD_NUMBER = 10;
    private java.util.List<com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage> grantedAuthority_;
    public java.util.List<com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage> getGrantedAuthorityList() {
      return grantedAuthority_;
    }
    public java.util.List<? extends com.cloudlbs.platform.protocol.UserAccountProto.RoleMessageOrBuilder> 
        getGrantedAuthorityOrBuilderList() {
      return grantedAuthority_;
    }
    public int getGrantedAuthorityCount() {
      return grantedAuthority_.size();
    }
    public com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage getGrantedAuthority(int index) {
      return grantedAuthority_.get(index);
    }
    public com.cloudlbs.platform.protocol.UserAccountProto.RoleMessageOrBuilder getGrantedAuthorityOrBuilder(
        int index) {
      return grantedAuthority_.get(index);
    }
    
    // optional string username = 11;
    public static final int USERNAME_FIELD_NUMBER = 11;
    private java.lang.Object username_;
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          username_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string displayName = 12;
    public static final int DISPLAYNAME_FIELD_NUMBER = 12;
    private java.lang.Object displayName_;
    public boolean hasDisplayName() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getDisplayName() {
      java.lang.Object ref = displayName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          displayName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDisplayNameBytes() {
      java.lang.Object ref = displayName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        displayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      guid_ = "";
      createDate_ = 0L;
      version_ = 0L;
      email_ = "";
      status_ = "";
      firstName_ = "";
      lastName_ = "";
      password_ = "";
      grantedAuthority_ = java.util.Collections.emptyList();
      username_ = "";
      displayName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, createDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getEmailBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getStatusBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(7, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, getLastNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(9, getPasswordBytes());
      }
      for (int i = 0; i < grantedAuthority_.size(); i++) {
        output.writeMessage(10, grantedAuthority_.get(i));
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(11, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(12, getDisplayNameBytes());
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, createDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, version_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getEmailBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getStatusBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getFirstNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getLastNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getPasswordBytes());
      }
      for (int i = 0; i < grantedAuthority_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, grantedAuthority_.get(i));
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getDisplayNameBytes());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage, Builder> implements com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudlbs.platform.protocol.UserAccountProto.internal_static_account_UserAccountMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudlbs.platform.protocol.UserAccountProto.internal_static_account_UserAccountMessage_fieldAccessorTable;
      }
      
      // Construct using com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGrantedAuthorityFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        guid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        createDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        firstName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        lastName_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        if (grantedAuthorityBuilder_ == null) {
          grantedAuthority_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          grantedAuthorityBuilder_.clear();
        }
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        displayName_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage.getDescriptor();
      }
      
      public com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage getDefaultInstanceForType() {
        return com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage.getDefaultInstance();
      }
      
      public com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage build() {
        com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage buildPartial() {
        com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage result = new com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.guid_ = guid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.createDate_ = createDate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.firstName_ = firstName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.lastName_ = lastName_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.password_ = password_;
        if (grantedAuthorityBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            grantedAuthority_ = java.util.Collections.unmodifiableList(grantedAuthority_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.grantedAuthority_ = grantedAuthority_;
        } else {
          result.grantedAuthority_ = grantedAuthorityBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.displayName_ = displayName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage) {
          return mergeFrom((com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage other) {
        if (other == com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage.getDefaultInstance()) return this;
        if (other.hasGuid()) {
          setGuid(other.getGuid());
        }
        if (other.hasCreateDate()) {
          setCreateDate(other.getCreateDate());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasFirstName()) {
          setFirstName(other.getFirstName());
        }
        if (other.hasLastName()) {
          setLastName(other.getLastName());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        if (grantedAuthorityBuilder_ == null) {
          if (!other.grantedAuthority_.isEmpty()) {
            if (grantedAuthority_.isEmpty()) {
              grantedAuthority_ = other.grantedAuthority_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureGrantedAuthorityIsMutable();
              grantedAuthority_.addAll(other.grantedAuthority_);
            }
            onChanged();
          }
        } else {
          if (!other.grantedAuthority_.isEmpty()) {
            if (grantedAuthorityBuilder_.isEmpty()) {
              grantedAuthorityBuilder_.dispose();
              grantedAuthorityBuilder_ = null;
              grantedAuthority_ = other.grantedAuthority_;
              bitField0_ = (bitField0_ & ~0x00000100);
              grantedAuthorityBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGrantedAuthorityFieldBuilder() : null;
            } else {
              grantedAuthorityBuilder_.addAllMessages(other.grantedAuthority_);
            }
          }
        }
        if (other.hasUsername()) {
          setUsername(other.getUsername());
        }
        if (other.hasDisplayName()) {
          setDisplayName(other.getDisplayName());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              guid_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              createDate_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              version_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              email_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              status_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000020;
              firstName_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000040;
              lastName_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000080;
              password_ = input.readBytes();
              break;
            }
            case 82: {
              com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.Builder subBuilder = com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGrantedAuthority(subBuilder.buildPartial());
              break;
            }
            case 90: {
              bitField0_ |= 0x00000200;
              username_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000400;
              displayName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string guid = 1;
      private java.lang.Object guid_ = "";
      public boolean hasGuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getGuid() {
        java.lang.Object ref = guid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          guid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGuid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
        return this;
      }
      public Builder clearGuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        guid_ = getDefaultInstance().getGuid();
        onChanged();
        return this;
      }
      void setGuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
      }
      
      // optional int64 createDate = 2;
      private long createDate_ ;
      public boolean hasCreateDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getCreateDate() {
        return createDate_;
      }
      public Builder setCreateDate(long value) {
        bitField0_ |= 0x00000002;
        createDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        createDate_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 version = 3;
      private long version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getVersion() {
        return version_;
      }
      public Builder setVersion(long value) {
        bitField0_ |= 0x00000004;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        version_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string email = 4;
      private java.lang.Object email_ = "";
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        email_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000008);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      void setEmail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        email_ = value;
        onChanged();
      }
      
      // optional string status = 5;
      private java.lang.Object status_ = "";
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStatus(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000010);
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      void setStatus(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        status_ = value;
        onChanged();
      }
      
      // optional string firstName = 7;
      private java.lang.Object firstName_ = "";
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFirstName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        firstName_ = value;
        onChanged();
        return this;
      }
      public Builder clearFirstName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      void setFirstName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        firstName_ = value;
        onChanged();
      }
      
      // optional string lastName = 8;
      private java.lang.Object lastName_ = "";
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLastName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        lastName_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastName() {
        bitField0_ = (bitField0_ & ~0x00000040);
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      void setLastName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        lastName_ = value;
        onChanged();
      }
      
      // optional string password = 9;
      private java.lang.Object password_ = "";
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPassword(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        password_ = value;
        onChanged();
        return this;
      }
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000080);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      void setPassword(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        password_ = value;
        onChanged();
      }
      
      // repeated .account.RoleMessage grantedAuthority = 10;
      private java.util.List<com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage> grantedAuthority_ =
        java.util.Collections.emptyList();
      private void ensureGrantedAuthorityIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          grantedAuthority_ = new java.util.ArrayList<com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage>(grantedAuthority_);
          bitField0_ |= 0x00000100;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage, com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.Builder, com.cloudlbs.platform.protocol.UserAccountProto.RoleMessageOrBuilder> grantedAuthorityBuilder_;
      
      public java.util.List<com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage> getGrantedAuthorityList() {
        if (grantedAuthorityBuilder_ == null) {
          return java.util.Collections.unmodifiableList(grantedAuthority_);
        } else {
          return grantedAuthorityBuilder_.getMessageList();
        }
      }
      public int getGrantedAuthorityCount() {
        if (grantedAuthorityBuilder_ == null) {
          return grantedAuthority_.size();
        } else {
          return grantedAuthorityBuilder_.getCount();
        }
      }
      public com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage getGrantedAuthority(int index) {
        if (grantedAuthorityBuilder_ == null) {
          return grantedAuthority_.get(index);
        } else {
          return grantedAuthorityBuilder_.getMessage(index);
        }
      }
      public Builder setGrantedAuthority(
          int index, com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage value) {
        if (grantedAuthorityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGrantedAuthorityIsMutable();
          grantedAuthority_.set(index, value);
          onChanged();
        } else {
          grantedAuthorityBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setGrantedAuthority(
          int index, com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.Builder builderForValue) {
        if (grantedAuthorityBuilder_ == null) {
          ensureGrantedAuthorityIsMutable();
          grantedAuthority_.set(index, builderForValue.build());
          onChanged();
        } else {
          grantedAuthorityBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addGrantedAuthority(com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage value) {
        if (grantedAuthorityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGrantedAuthorityIsMutable();
          grantedAuthority_.add(value);
          onChanged();
        } else {
          grantedAuthorityBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addGrantedAuthority(
          int index, com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage value) {
        if (grantedAuthorityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGrantedAuthorityIsMutable();
          grantedAuthority_.add(index, value);
          onChanged();
        } else {
          grantedAuthorityBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addGrantedAuthority(
          com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.Builder builderForValue) {
        if (grantedAuthorityBuilder_ == null) {
          ensureGrantedAuthorityIsMutable();
          grantedAuthority_.add(builderForValue.build());
          onChanged();
        } else {
          grantedAuthorityBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addGrantedAuthority(
          int index, com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.Builder builderForValue) {
        if (grantedAuthorityBuilder_ == null) {
          ensureGrantedAuthorityIsMutable();
          grantedAuthority_.add(index, builderForValue.build());
          onChanged();
        } else {
          grantedAuthorityBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllGrantedAuthority(
          java.lang.Iterable<? extends com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage> values) {
        if (grantedAuthorityBuilder_ == null) {
          ensureGrantedAuthorityIsMutable();
          super.addAll(values, grantedAuthority_);
          onChanged();
        } else {
          grantedAuthorityBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearGrantedAuthority() {
        if (grantedAuthorityBuilder_ == null) {
          grantedAuthority_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          grantedAuthorityBuilder_.clear();
        }
        return this;
      }
      public Builder removeGrantedAuthority(int index) {
        if (grantedAuthorityBuilder_ == null) {
          ensureGrantedAuthorityIsMutable();
          grantedAuthority_.remove(index);
          onChanged();
        } else {
          grantedAuthorityBuilder_.remove(index);
        }
        return this;
      }
      public com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.Builder getGrantedAuthorityBuilder(
          int index) {
        return getGrantedAuthorityFieldBuilder().getBuilder(index);
      }
      public com.cloudlbs.platform.protocol.UserAccountProto.RoleMessageOrBuilder getGrantedAuthorityOrBuilder(
          int index) {
        if (grantedAuthorityBuilder_ == null) {
          return grantedAuthority_.get(index);  } else {
          return grantedAuthorityBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.cloudlbs.platform.protocol.UserAccountProto.RoleMessageOrBuilder> 
           getGrantedAuthorityOrBuilderList() {
        if (grantedAuthorityBuilder_ != null) {
          return grantedAuthorityBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(grantedAuthority_);
        }
      }
      public com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.Builder addGrantedAuthorityBuilder() {
        return getGrantedAuthorityFieldBuilder().addBuilder(
            com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.getDefaultInstance());
      }
      public com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.Builder addGrantedAuthorityBuilder(
          int index) {
        return getGrantedAuthorityFieldBuilder().addBuilder(
            index, com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.getDefaultInstance());
      }
      public java.util.List<com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.Builder> 
           getGrantedAuthorityBuilderList() {
        return getGrantedAuthorityFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage, com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.Builder, com.cloudlbs.platform.protocol.UserAccountProto.RoleMessageOrBuilder> 
          getGrantedAuthorityFieldBuilder() {
        if (grantedAuthorityBuilder_ == null) {
          grantedAuthorityBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage, com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.Builder, com.cloudlbs.platform.protocol.UserAccountProto.RoleMessageOrBuilder>(
                  grantedAuthority_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          grantedAuthority_ = null;
        }
        return grantedAuthorityBuilder_;
      }
      
      // optional string username = 11;
      private java.lang.Object username_ = "";
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUsername(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        username_ = value;
        onChanged();
        return this;
      }
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000200);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      void setUsername(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        username_ = value;
        onChanged();
      }
      
      // optional string displayName = 12;
      private java.lang.Object displayName_ = "";
      public boolean hasDisplayName() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getDisplayName() {
        java.lang.Object ref = displayName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          displayName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDisplayName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        displayName_ = value;
        onChanged();
        return this;
      }
      public Builder clearDisplayName() {
        bitField0_ = (bitField0_ & ~0x00000400);
        displayName_ = getDefaultInstance().getDisplayName();
        onChanged();
        return this;
      }
      void setDisplayName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        displayName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:account.UserAccountMessage)
    }
    
    static {
      defaultInstance = new UserAccountMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:account.UserAccountMessage)
    public static final int ITEMS_FIELD_NUMBER = 1002;
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.cloudlbs.platform.protocol.SearchProto.SearchResultMessage,
        java.util.List<com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage>> items = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage.getDefaultInstance(),
          0,
          com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage.class,
          com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage.getDefaultInstance());
  }
  
  public interface RoleMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string guid = 1;
    boolean hasGuid();
    String getGuid();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
  }
  public static final class RoleMessage extends
      com.google.protobuf.GeneratedMessage
      implements RoleMessageOrBuilder {
    // Use RoleMessage.newBuilder() to construct.
    private RoleMessage(Builder builder) {
      super(builder);
    }
    private RoleMessage(boolean noInit) {}
    
    private static final RoleMessage defaultInstance;
    public static RoleMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoleMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloudlbs.platform.protocol.UserAccountProto.internal_static_account_RoleMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloudlbs.platform.protocol.UserAccountProto.internal_static_account_RoleMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string guid = 1;
    public static final int GUID_FIELD_NUMBER = 1;
    private java.lang.Object guid_;
    public boolean hasGuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getGuid() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          guid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGuidBytes() {
      java.lang.Object ref = guid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      guid_ = "";
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cloudlbs.platform.protocol.UserAccountProto.RoleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloudlbs.platform.protocol.UserAccountProto.internal_static_account_RoleMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloudlbs.platform.protocol.UserAccountProto.internal_static_account_RoleMessage_fieldAccessorTable;
      }
      
      // Construct using com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        guid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.getDescriptor();
      }
      
      public com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage getDefaultInstanceForType() {
        return com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.getDefaultInstance();
      }
      
      public com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage build() {
        com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage buildPartial() {
        com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage result = new com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.guid_ = guid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage) {
          return mergeFrom((com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage other) {
        if (other == com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.getDefaultInstance()) return this;
        if (other.hasGuid()) {
          setGuid(other.getGuid());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              guid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string guid = 1;
      private java.lang.Object guid_ = "";
      public boolean hasGuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getGuid() {
        java.lang.Object ref = guid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          guid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGuid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
        return this;
      }
      public Builder clearGuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        guid_ = getDefaultInstance().getGuid();
        onChanged();
        return this;
      }
      void setGuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        guid_ = value;
        onChanged();
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:account.RoleMessage)
    }
    
    static {
      defaultInstance = new RoleMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:account.RoleMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_account_UserAccountMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_UserAccountMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_account_RoleMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_RoleMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UserAccount.proto\022\007account\032\014search.pro" +
      "to\"\311\002\n\022UserAccountMessage\022\014\n\004guid\030\001 \001(\t\022" +
      "\022\n\ncreateDate\030\002 \001(\003\022\017\n\007version\030\003 \001(\003\022\r\n\005" +
      "email\030\004 \001(\t\022\016\n\006status\030\005 \001(\t\022\021\n\tfirstName" +
      "\030\007 \001(\t\022\020\n\010lastName\030\010 \001(\t\022\020\n\010password\030\t \001" +
      "(\t\022.\n\020grantedAuthority\030\n \003(\0132\024.account.R" +
      "oleMessage\022\020\n\010username\030\013 \001(\t\022\023\n\013displayN" +
      "ame\030\014 \001(\t*\t\010\350\007\020\200\200\200\200\0022H\n\005items\022\033.search.S" +
      "earchResultMessage\030\352\007 \003(\0132\033.account.User" +
      "AccountMessage\")\n\013RoleMessage\022\014\n\004guid\030\001 ",
      "\001(\t\022\014\n\004name\030\002 \001(\tB2\n\036com.cloudlbs.platfo" +
      "rm.protocolB\020UserAccountProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_account_UserAccountMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_account_UserAccountMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_account_UserAccountMessage_descriptor,
              new java.lang.String[] { "Guid", "CreateDate", "Version", "Email", "Status", "FirstName", "LastName", "Password", "GrantedAuthority", "Username", "DisplayName", },
              com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage.class,
              com.cloudlbs.platform.protocol.UserAccountProto.UserAccountMessage.Builder.class);
          internal_static_account_RoleMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_account_RoleMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_account_RoleMessage_descriptor,
              new java.lang.String[] { "Guid", "Name", },
              com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.class,
              com.cloudlbs.platform.protocol.UserAccountProto.RoleMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cloudlbs.platform.protocol.SearchProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
